name: Use reusable workflow

on:
  push:
    branches:
      - '**'

jobs:
  check_rebase:
    uses: Emile-2/reusable_workflw/.github/workflows/check_reabse.yml@main
    with:
      branch: ${{ github.ref_name }}
