name: Check Rebase Status

on:  
  push:
    branches: 
      - 'feature/**' # Wildcard pattern to match feature branches

jobs:
  rebase-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' 
      - name: Install GitPython
        run: pip install GitPython
      - name: Run rebase check script
        run: python rebase_check.py  
      - name: Take action based on result (optional)
        if: ${{ steps.rebase-check.outputs.needs_rebase == 'true' }} 
        run: |  
          echo "Feature branch needs rebase!"
          # Add more actions here: comment on PR, send notification, etc.
