name: Enforce Rebase Before Merge

on: 
  push:
    branches-ignore: [ main ]  
  pull_request: 

jobs:
  enforce_rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for Rebase
        if: ${{ github.event.pull_request }}  # Ensure we're in a pull request context
        run: |
          if [[ -n $(git log --oneline main..HEAD) ]]; then
            echo "::error::Feature branch needs to be rebased on top of main before merging. Please rebase locally."
            exit 1 
          fi

      - name: Report Success
        if: ${{ github.event.pull_request }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.after,  
              state: 'success',
              description: 'Feature branch is rebased!',
              context: 'Rebase Check' 
            });
