name: Check Feature Branch Rebasing

on:
  pull_request:

jobs:
  check-rebasing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get base SHA
        run: echo "BASE_SHA=$(git rev-parse origin/main)" >> $GITHUB_ENV

      - name: Check for linear history
        run: |
          git fetch origin main
          git branch --contains origin/main > branches.txt
          if grep -q $(git rev-parse HEAD) branches.txt; then
            echo "Pull request commits appear to be linear on top of main branch. Rebasing is not necessary."
          else
            echo "Pull request commits do not appear to be a linear history on top of main branch. Consider rebasing your branch for a cleaner integration."
          fi
