name: Enforce Feature Branch Rebase (Informational)

on: 
  pull_request_target: 
    types: [opened, synchronize]
    branches:
      - main

jobs:
  enforce_rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for Rebase
        run: |
          if [[ -n $(git log --oneline main..HEAD) ]]; then
            echo "::warning::Feature branch needs to be rebased on top of main before merging. Please rebase locally."
            exit 0  # Allow the workflow to succeed, but with a warning
          else
            echo "Feature branch is up-to-date with main."
          fi
