name: Rebase Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  rebase_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check rebase
      run: |
        git fetch origin main
        git checkout main
        git reset --hard origin/main
        git checkout ${{ github.event.pull_request.head.ref }}
        git rebase main
        if [ $? -eq 0 ]; then
          echo "Rebase successful."
          exit 0
        else
          echo "Rebase failed. Please rebase your branch onto main."
          exit 1
        fi
