name: Check Rebase

on:
  pull_request:
    branches:
      - main

jobs:

  check-rebase:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required to fetch the entire branch history

    - name: Check if rebased
      id: check-rebase
      run: |
        main_branch_commit=$(git rev-parse origin/main)
        echo "main_branch_commit=$main_branch_commit" >> $GITHUB_OUTPUT

        feature_branch_commit=$(git rev-parse HEAD)
        echo "feature_branch_commit=$feature_branch_commit" >> $GITHUB_OUTPUT

        rebased=$(git merge-base --is-ancestor $main_branch_commit $feature_branch_commit; echo $?)
        if [[ $rebased -eq 0 ]]; then
          echo "rebased=true" >> $GITHUB_OUTPUT
        else
          echo "rebased=false" >> $GITHUB_OUTPUT
        fi

    - name: Check rebase status
      if: steps.check-rebase.outputs.rebased == 'false'
      run: |
        echo "The feature branch has not been rebased onto main."
        exit 1
