name: Debug Trigger

on: 
  push:
  pull_request:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "---------------------------------------"
          echo "Event Name: ${{ github.event_name }}" 
          echo "Event Action: ${{ github.event.action }}" # For pull requests
          echo "Base Ref: ${{ github.event.pull_request.base.ref }}" 
          echo "Head Ref: ${{ github.event.pull_request.head.ref }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "---------------------------------------"
