name: Enforce Rebase Policy

on: 
  pull_request:
    branches: [ main ]  # Trigger when pull requests are opened/updated targeting 'main'

jobs:
  check_rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for required rebase
        run: |
          hash1=$(git show-ref --heads -s origin/main)  # Get latest commit on remote 'main'
          hash2=$(git merge-base origin/main HEAD)    # 'HEAD' refers to the current branch
          [ "${hash1}" = "${hash2}" ] && echo "OK - Rebase not needed" || echo "Error: Rebase is required"
