name: Check Feature Branch Rebase

on: 
  pull_request:
    branches: [ main ]  

jobs:
  check-rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        
      - name: Check if Rebase is Needed
        run: |
          git fetch origin main 
          LATEST_FEATURE_COMMIT=$(git rev-parse HEAD)  
          MERGE_BASE=$(git merge-base HEAD origin/main)

          if [[ "$LATEST_FEATURE_COMMIT" != "$MERGE_BASE" ]]; then
            echo "rebase"
          else
            echo "dont rebase"
          fi

 
