name: Check Feature Branch Rebase

on: 
  pull_request:
    branches: [ main ]  

jobs:
  check-rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        
      - name: Check if Rebase is Needed
        id: rebase_check
        run: |
          git fetch origin main 
          MERGE_BASE=$(git merge-base HEAD origin/main)  
          LATEST_FEATURE_COMMIT=$(git rev-parse HEAD)

          if [[ "$MERGE_BASE" != "$LATEST_FEATURE_COMMIT" ]]; then
            echo "::set-output name=needs-rebase::true"
          else
            echo "::set-output name=needs-rebase::false"
          fi

      - name: Notify if Rebase Needed 
        if: ${{ steps.rebase_check.outputs.needs-rebase == 'true' }} 
        run: |
          echo "Feature branch is not up-to-date with main. Please rebase!"
